### ISSUE TITLE
problems with modules

### ISSUE THREAD

**Issue by irinatu** [Weeks-UNC/QuShape#1]
Dear Sir,
I tried to run QuSHape on my linux with python3 and pyqt5 (pyqt4 is already not available), while there are problems with dependencies. seqDialogs.py is in Dialogs folder, but it looks like in __init__.py it should be "from  Dialog.seqDialogs import *" instead of "from seqDialogs import *". As well as other imported modules

python mainWindow.py
Traceback (most recent call last):
  File "/home/irina/bin/QuShape/src/mainWindow.py", line 1, in <module>
    from funcMainWin import *
  File "/home/irina/bin/QuShape/src/funcMainWin.py", line 1, in <module>
    from imports import *
  File "/home/irina/bin/QuShape/src/imports.py", line 40, in <module>
    from Dialogs import *
  File "/home/irina/bin/QuShape/src/Dialogs/__init__.py", line 1, in <module>
    from seqDialogs import *
ModuleNotFoundError: No module named 'seqDialogs'

**Comment by Psirving** [comment]
These are valid import statements in Python 2, but not Python 3. You have a few options.

1. Reinstall QuShape in a Python 2 environment.
2. Convert the python files to Python 3 using 2to3.py.
3. Use a newer experimental method such as SHAPE-MaP and analyze with ShapeMapper2. (recommended if possible)

To my knowledge, QuShape has not been updated in about 10 years. You might encounter other issues with compatibility.
